### ISSUE TITLE
[BUG] - Compilation failure with Nextjs 15

### ISSUE THREAD

**Issue by xavierchow** [nextui-org/nextui#4139]
### NextUI Version

2.5.0-beta.19

### Describe the bug

I tried nextjs 15 & react 19 rc with beta version 2.5.0-beta.19, it still doesn't work, I got the compilation failure with react 19 rc.

```
Build Error
Next.js (15.0.3)
Failed to compile

./node_modules/@nextui-org/calendar/dist/chunk-KHWTYBU3.mjs
Error:   × The "use client" directive must be placed before other expressions. Move it to the top of the file to resolve this issue.
     ╭─[/Users/xavier/dev/react19Exp/test-react19/node_modules/@nextui-org/calendar/dist/chunk-KHWTYBU3.mjs:113:1]
 110 │ 
 111 │ // ../../../node_modules/.pnpm/framer-motion@11.9.0_@emotion+is-prop-valid@1.3.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/framer-motion/dist/es/context/MotionConfigContext.mjs
 112 │ import { createContext } from "react";
 113 │ "use client";
     · ─────────────
 114 │ var MotionConfigContext = createContext({
 115 │   transformPagePoint: (p) => p,
 116 │   isStatic: false,
     ╰────
(and more similar errors ...  )
```

### Your Example Website or App

https://github.com/xavierchow/nextui-with-react19-rc/

### Steps to Reproduce the Bug or Issue

1. npm install
2. npm run dev
3. access the url http://localhost:3000/wall

### Expected behavior

I expected the page can be compiled and rendered but I saw the compilation failure.

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment]
Just an update. It works If you use an individual package. For global package, may wait for the linked PR to be merged.

**Comment by wingkwong** [comment]
For global package, please use `2.5.0-beta.24`.

![image](https://github.com/user-attachments/assets/18fdd413-66a9-42cb-8dca-d929793e0528)

 I've also modified the following files. Here's the changes for your reference.

package.json
```json
{
	"name": "test-react19",
	"version": "0.1.0",
	"private": true,
	"scripts": {
		"dev": "next dev",
		"build": "next build",
		"start": "next start",
		"lint": "next lint"
	},
	"dependencies": {
		"@nextui-org/react": "^2.5.0-beta.24",
		"framer-motion": "12.0.0-alpha.2",
		"next": "^15.0.0-rc.1",
		"react": "19.0.0-rc-cd22717c-20241013",
		"react-dom": "19.0.0-rc-cd22717c-20241013"
	},
	"devDependencies": {
		"@types/node": "^20",
		"@types/react": "npm:types-react@rc",
		"@types/react-dom": "npm:types-react-dom@rc",
		"eslint": "^8",
		"eslint-config-next": "15.0.3",
		"eslint-plugin-jsdoc": "^46.9.1",
		"postcss": "^8",
		"tailwindcss": "^3.4.1",
		"typescript": "^5"
	},
	"overrides": {
		"@types/react": "npm:types-react@rc",
		"@types/react-dom": "npm:types-react-dom@rc",
		"@nextui-org/*": {
			"framer-motion": "12.0.0-alpha.2"
		},
		"framer-motion": {
			"react": "19.0.0-rc-cd22717c-20241013",
			"react-dom": "19.0.0-rc-cd22717c-20241013"
		}
	}
}
```

tailwind.config.ts

```ts
import type { Config } from "tailwindcss";
import {nextui} from "@nextui-org/react"

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
    },
  },
  plugins: [nextui()],
} satisfies Config;
```

page.tsx

```tsx
'use client'

import { Card, CardBody } from '@nextui-org/react';
export default function CardInWall() {
  return (
    <Card>
      <CardBody>
        <p>Make beautiful websites regardless of your design experience.</p>
      </CardBody>
    </Card>
  );
}
```

**Comment by xavierchow** [comment]
@wingkwong thank you for your quick response, it works with react `19.0.0-rc-cd22717c-20241013`
regarding my case, I'm using a later rc version `19.0.0-rc-66855b96-20241106`, it shows compilation error as follows,
```
Failed to compile.

./app/globals.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[13].oneOf[10].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[13].oneOf[10].use[3]!./app/globals.css
TypeError: Cannot read properties of undefined (reading 'ReactCurrentBatchConfig')
    at /Users/xavzhou/github/nextui-with-react19-rc/node_modules/@nextui-org/use-aria-accordion/node_modules/react-dom/cjs/react-dom.production.min.js:72:402
    at evalModule (/Users/xavzhou/github/nextui-with-react19-rc/node_modules/jiti/dist/jiti.js:1:247313)
    at jiti (/Users/xavzhou/github/nextui-with-react19-rc/node_modules/jiti/dist/jiti.js:1:245241)
    at /Users/xavzhou/github/nextui-with-react19-rc/node_modules/@nextui-org/use-aria-accordion/node_modules/react-dom/index.js:35:20
    at evalModule (/Users/xavzhou/github/nextui-with-react19-rc/node_modules/jiti/dist/jiti.js:1:247313)
    at jiti (/Users/xavzhou/github/nextui-with-react19-rc/node_modules/jiti/dist/jiti.js:1:245241)
    at /Users/xavzhou/github/nextui-with-react19-rc/node_modules/@nextui-org/use-aria-accordion/node_modules/@react-aria/selection/dist/useSelectableCollection.main.js:3:23
    at evalModule (/Users/xavzhou/github/nextui-with-react19-rc/node_modules/jiti/dist/jiti.js:1:247313)
    at jiti (/Users/xavzhou/github/nextui-with-react19-rc/node_modules/jiti/dist/jiti.js:1:245241)
    at /Users/xavzhou/github/nextui-with-react19-rc/node_modules/@nextui-org/use-aria-accordion/node_modules/@react-aria/selection/dist/main.js:1:108
```

but as long as the individual package works, it won't be a blocker for me; I probably will try the global install again once the react 19 is released, thanks.

**Comment by xavierchow** [comment]
@wingkwong I just realized that if I stick to next.js `15.0.3` it raises the aforementioned compilation error.
If I use next.js `15.0.0-rc.1` it works with react `19.0.0-rc-66855b96-20241106`.

I also pushed my code to a new branch `fixed-version`: https://github.com/xavierchow/nextui-with-react19-rc/tree/fixed-version, you can have a try.

**Comment by alienbuild** [comment]
I'm also getting a compilation error for `@nextui-org/react": "2.5.0-beta.26`

```
./node_modules/@nextui-org/react/dist/index.mjs
Error:   × The "use client" directive must be placed before other expressions. Move it to the top of the file to resolve this issue.
    ╭─[C:\Users\****\_git\****\****\node_modules\@nextui-org\react\dist\index.mjs:52:1]
 49 │ export * from "@nextui-org/input-otp";
 50 │ import { VisuallyHidden } from "@react-aria/visually-hidden";
 51 │ import { ResizablePanel } from "@nextui-org/framer-utils";
 52 │ "use client";
    · ─────────────
 53 │ export {
 54 │   ResizablePanel,
 55 │   VisuallyHidden
    ╰────
```

Fixed by commenting out the second "use client" at the bottom of the index.mjs in the dist folder.
