### ISSUE TITLE
[BUG] - Switch - TypeError: slots.hiddenInput is not a function

### ISSUE THREAD

**Issue by pdiegolopez** [nextui-org/nextui#4348]
### NextUI Version

@nextui-org/switch@2.2.6

### Describe the bug

After update from 2.2.4 Switch component is broken with this error in console:

TypeError: slots.hiddenInput is not a function

### Steps to Reproduce the Bug or Issue

1. Run dev mode with yarn run dev
2. Try to render a page with Switch component

### Expected behavior

Render page without error

### Operating System Version

macOS

### Browser

Chrome

**Comment by oliverpechey** [comment]
I'm also getting this when trying to use the Checkbox.

**Comment by t8y2** [comment]
> I'm also getting this when trying to use the Checkbox.

me too
